name: Check Frontend

on:
  push:
    branches: [main]

concurrency:
  group: check-frontend
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_LIFF_ID: "2009434684-FmIDtNRF"
          NEXT_PUBLIC_API_URL: "https://api.talkrai.app"

